#
# Copyright © 2016-2020 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tb-node
  namespace: thingsboard
spec:
  serviceName: tb-node
  replicas: 1
  selector:
    matchLabels:
      app: tb-node
  template:
    metadata:
      labels:
        app: tb-node
    spec:
      volumes:
        - name: tb-node-config
          configMap:
            name: tb-node-config
            items:
            - key: conf
              path:  thingsboard.conf
            - key: logback
              path:  logback.xml
        - name: tb-node-logs
          emptyDir: {}
        # Uncomment the following lines to enable two-way MQTTS
        #- name: tb-mqtts-config
        #  configMap:
        #    name: tb-mqtts-config
        #    items:
        #      - key: server.jks
        #        path:  server.jks
        # Uncomment the following lines to enable two-way lwM2Ms
        #- name: tb-lwm2ms-config
        #  configMap:
        #    name: tb-lwm2ms-config
        #    items:
        #      - key: server.jks
        #        path:  server.jks
      containers:
      - name: server
        imagePullPolicy: Always
        image: thingsboard/tb-node:3.3.1
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 1883
          name: mqtt
        - containerPort: 8883
          name: mqtts
        - containerPort: 5683
          name: coap
          protocol: UDP
        #- containerPort: 5684
        #  name: coaps
        #  protocol: UDP
        - containerPort: 7070
          name: edge
        - containerPort: 5685
          name: lwm2m
          protocol: UDP
        #- containerPort: 5687
        #  name: lwm2bs
        # protocol: UDP
        #- containerPort: 5688
        #  name: lwm2s
        #  protocol: UDP
        env:
        - name: TB_SERVICE_TYPE
          value: "monolith"
        - name: TB_QUEUE_TYPE
          value: "in-memory"
        - name: HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE
          value: "false"
        #- name: LWM2M_KEYSTORE
        #  value: "/ssl-config/lwm2mserver.jks"
        #- name: LWM2M_ENABLED_BS
        #  value: "false"
        # Uncomment the following lines to enable two-way MQTTS
        #- name: MQTT_SSL_ENABLED
        #  value: "true"
        #- name: MQTT_SSL_BIND_ADDRESS
        #  value: "0.0.0.0"
        #- name: MQTT_SSL_BIND_PORT
        #  value: "8883"
        #- name: MQTT_SSL_KEY_STORE
        #  value: "/ssl-config/server.jks"
        #- name: MQTT_SSL_KEY_STORE_PASSWORD
        #  value: ""
        #- name: MQTT_SSL_KEY_PASSWORD
        #  value: ""
        envFrom:
        - configMapRef:
            name: tb-node-db-config
        volumeMounts:
          - mountPath: /config
            name: tb-node-config
          - mountPath: /var/log/thingsboard
            name: tb-node-logs
          # Uncomment the following lines to enable two-way MQTTS
          #- mountPath: /ssl-config
          #  name: tb-mqtts-config
          # Uncomment the following lines to enable two-way lwM2Ms
          #- mountPath: /ssl-config
          #  name: tb-lwm2ms-config
        readinessProbe:
          httpGet:
            path: /login
            port: http
        livenessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: 460
          timeoutSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tb-node
  namespace: thingsboard
spec:
  type: ClusterIP
  selector:
    app: tb-node
  ports:
    - port: 8080
      name: http
